### ISSUE TITLE
ClosestPointPairAlgorithm: Illegal initial capacity: -1

### ISSUE THREAD

**Issue by micycle1** [KevinStern/software-and-algorithms#16]
For most input point sets, the `ClosestPointPairAlgorithm.execute()` has the following error:

```
java.lang.IllegalArgumentException: Illegal initial capacity: -1
	at java.base/java.util.HashMap.<init>(HashMap.java:444)
	at java.base/java.util.HashMap.<init>(HashMap.java:463)
	at java.base/java.util.HashSet.<init>(HashSet.java:145)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:130)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:156)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:156)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:156)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.closestPair(ClosestPointPairAlgorithm.java:152)
	at micycle.pgs.utility.ClosestPointPairAlgorithm.execute(ClosestPointPairAlgorithm.java:208)
```

`mid - low` is becoming negative?

**Comment by KevinStern** [comment]
Thanks for reporting.  Fixed.

I was calculating mid using lo / 2 + hi / 2, which, because of truncation, can differ from (lo + hi) / 2.  Elsewhere, I rely on the behavior of the latter by assuming that since I don't calculate mid unless size is at least 4, size will never be 1.
